//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опр штат расп.
    /// </summary>
    // *** Start programmer edit section *** (ОпрШтатРасп CustomAttributes)

    // *** End programmer edit section *** (ОпрШтатРасп CustomAttributes)
    [AutoAltered()]
    [Caption("Опр штат расп")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОпрШтатРаспE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Период as \'Период\'",
            "Гостиница as \'Гостиница\'",
            "Гостиница.Наименование as \'Наименование\'",
            "Директор as \'Директор\'",
            "Директор.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Гостиница.Наименование",
            "Директор.ФИО"})]
    [MasterViewDefineAttribute("ОпрШтатРаспE", "Гостиница", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОпрШтатРаспE", "Директор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОпрШтатРаспL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Период as \'Период\'",
            "Гостиница.Наименование as \'Наименование\'",
            "Директор.ФИО as \'ФИО\'"})]
    public class ОпрШтатРасп : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private System.DateTime fПериод;
        
        private IIS.Gostinica1.Гостиница fГостиница;
        
        private IIS.Gostinica1.Директор fДиректор;
        
        // *** Start programmer edit section *** (ОпрШтатРасп CustomMembers)

        // *** End programmer edit section *** (ОпрШтатРасп CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОпрШтатРасп.Дата CustomAttributes)

        // *** End programmer edit section *** (ОпрШтатРасп.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Дата Get start)

                // *** End programmer edit section *** (ОпрШтатРасп.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОпрШтатРасп.Дата Get end)

                // *** End programmer edit section *** (ОпрШтатРасп.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Дата Set start)

                // *** End programmer edit section *** (ОпрШтатРасп.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОпрШтатРасп.Дата Set end)

                // *** End programmer edit section *** (ОпрШтатРасп.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ОпрШтатРасп.Номер CustomAttributes)

        // *** End programmer edit section *** (ОпрШтатРасп.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Номер Get start)

                // *** End programmer edit section *** (ОпрШтатРасп.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ОпрШтатРасп.Номер Get end)

                // *** End programmer edit section *** (ОпрШтатРасп.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Номер Set start)

                // *** End programmer edit section *** (ОпрШтатРасп.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ОпрШтатРасп.Номер Set end)

                // *** End programmer edit section *** (ОпрШтатРасп.Номер Set end)
            }
        }
        
        /// <summary>
        /// Период.
        /// </summary>
        // *** Start programmer edit section *** (ОпрШтатРасп.Период CustomAttributes)

        // *** End programmer edit section *** (ОпрШтатРасп.Период CustomAttributes)
        public virtual System.DateTime Период
        {
            get
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Период Get start)

                // *** End programmer edit section *** (ОпрШтатРасп.Период Get start)
                System.DateTime result = this.fПериод;
                // *** Start programmer edit section *** (ОпрШтатРасп.Период Get end)

                // *** End programmer edit section *** (ОпрШтатРасп.Период Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Период Set start)

                // *** End programmer edit section *** (ОпрШтатРасп.Период Set start)
                this.fПериод = value;
                // *** Start programmer edit section *** (ОпрШтатРасп.Период Set end)

                // *** End programmer edit section *** (ОпрШтатРасп.Период Set end)
            }
        }
        
        /// <summary>
        /// Опр штат расп.
        /// </summary>
        // *** Start programmer edit section *** (ОпрШтатРасп.Гостиница CustomAttributes)

        // *** End programmer edit section *** (ОпрШтатРасп.Гостиница CustomAttributes)
        [PropertyStorage(new string[] {
                "Гостиница"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Гостиница Гостиница
        {
            get
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Гостиница Get start)

                // *** End programmer edit section *** (ОпрШтатРасп.Гостиница Get start)
                IIS.Gostinica1.Гостиница result = this.fГостиница;
                // *** Start programmer edit section *** (ОпрШтатРасп.Гостиница Get end)

                // *** End programmer edit section *** (ОпрШтатРасп.Гостиница Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Гостиница Set start)

                // *** End programmer edit section *** (ОпрШтатРасп.Гостиница Set start)
                this.fГостиница = value;
                // *** Start programmer edit section *** (ОпрШтатРасп.Гостиница Set end)

                // *** End programmer edit section *** (ОпрШтатРасп.Гостиница Set end)
            }
        }
        
        /// <summary>
        /// Опр штат расп.
        /// </summary>
        // *** Start programmer edit section *** (ОпрШтатРасп.Директор CustomAttributes)

        // *** End programmer edit section *** (ОпрШтатРасп.Директор CustomAttributes)
        [PropertyStorage(new string[] {
                "Директор"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Директор Директор
        {
            get
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Директор Get start)

                // *** End programmer edit section *** (ОпрШтатРасп.Директор Get start)
                IIS.Gostinica1.Директор result = this.fДиректор;
                // *** Start programmer edit section *** (ОпрШтатРасп.Директор Get end)

                // *** End programmer edit section *** (ОпрШтатРасп.Директор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОпрШтатРасп.Директор Set start)

                // *** End programmer edit section *** (ОпрШтатРасп.Директор Set start)
                this.fДиректор = value;
                // *** Start programmer edit section *** (ОпрШтатРасп.Директор Set end)

                // *** End programmer edit section *** (ОпрШтатРасп.Директор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОпрШтатРаспE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпрШтатРаспE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпрШтатРаспE", typeof(IIS.Gostinica1.ОпрШтатРасп));
                }
            }
            
            /// <summary>
            /// "ОпрШтатРаспL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпрШтатРаспL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпрШтатРаспL", typeof(IIS.Gostinica1.ОпрШтатРасп));
                }
            }
        }
    }
}
