//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расп об сотр.
    /// </summary>
    // *** Start programmer edit section *** (РаспОбСотр CustomAttributes)

    // *** End programmer edit section *** (РаспОбСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Расп об сотр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РаспОбСотрE", new string[] {
            "РегНомер as \'Рег номер\'",
            "Место as \'Место\'",
            "Дата as \'Дата\'",
            "Наименование as \'Наименование\'",
            "Гостиница as \'Гостиница\'",
            "Гостиница.Наименование as \'Наименование\'",
            "Директор as \'Директор\'",
            "Директор.ФИО as \'ФИО\'",
            "ТЧРаспОбСотр as \'Т ч расп об сотр\'",
            "ТЧРаспОбСотр.Обязанности as \'Обязанности\'"}, Hidden=new string[] {
            "Гостиница.Наименование",
            "Директор.ФИО",
            "ТЧРаспОбСотр.Обязанности"})]
    [MasterViewDefineAttribute("РаспОбСотрE", "Гостиница", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("РаспОбСотрE", "Директор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("РаспОбСотрE", "ТЧРаспОбСотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Обязанности")]
    [View("РаспОбСотрL", new string[] {
            "РегНомер as \'Рег номер\'",
            "Место as \'Место\'",
            "Дата as \'Дата\'",
            "Наименование as \'Наименование\'",
            "Гостиница.Наименование as \'Наименование\'",
            "Директор.ФИО as \'ФИО\'",
            "ТЧРаспОбСотр.Обязанности as \'Обязанности\'"})]
    public class РаспОбСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fРегНомер;
        
        private string fМесто;
        
        private System.DateTime fДата;
        
        private string fНаименование;
        
        private IIS.Gostinica1.Гостиница fГостиница;
        
        private IIS.Gostinica1.Директор fДиректор;
        
        private IIS.Gostinica1.ТЧРаспОбСотр fТЧРаспОбСотр;
        
        // *** Start programmer edit section *** (РаспОбСотр CustomMembers)

        // *** End programmer edit section *** (РаспОбСотр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.Дата CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.Дата Get start)

                // *** End programmer edit section *** (РаспОбСотр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РаспОбСотр.Дата Get end)

                // *** End programmer edit section *** (РаспОбСотр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.Дата Set start)

                // *** End programmer edit section *** (РаспОбСотр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РаспОбСотр.Дата Set end)

                // *** End programmer edit section *** (РаспОбСотр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.Место CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.Место CustomAttributes)
        [StrLen(255)]
        public virtual string Место
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.Место Get start)

                // *** End programmer edit section *** (РаспОбСотр.Место Get start)
                string result = this.fМесто;
                // *** Start programmer edit section *** (РаспОбСотр.Место Get end)

                // *** End programmer edit section *** (РаспОбСотр.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.Место Set start)

                // *** End programmer edit section *** (РаспОбСотр.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (РаспОбСотр.Место Set end)

                // *** End programmer edit section *** (РаспОбСотр.Место Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.Наименование CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.Наименование Get start)

                // *** End programmer edit section *** (РаспОбСотр.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (РаспОбСотр.Наименование Get end)

                // *** End programmer edit section *** (РаспОбСотр.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.Наименование Set start)

                // *** End programmer edit section *** (РаспОбСотр.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (РаспОбСотр.Наименование Set end)

                // *** End programmer edit section *** (РаспОбСотр.Наименование Set end)
            }
        }
        
        /// <summary>
        /// РегНомер.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.РегНомер CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.РегНомер CustomAttributes)
        [StrLen(255)]
        public virtual string РегНомер
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.РегНомер Get start)

                // *** End programmer edit section *** (РаспОбСотр.РегНомер Get start)
                string result = this.fРегНомер;
                // *** Start programmer edit section *** (РаспОбСотр.РегНомер Get end)

                // *** End programmer edit section *** (РаспОбСотр.РегНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.РегНомер Set start)

                // *** End programmer edit section *** (РаспОбСотр.РегНомер Set start)
                this.fРегНомер = value;
                // *** Start programmer edit section *** (РаспОбСотр.РегНомер Set end)

                // *** End programmer edit section *** (РаспОбСотр.РегНомер Set end)
            }
        }
        
        /// <summary>
        /// Расп об сотр.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.Гостиница CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.Гостиница CustomAttributes)
        [PropertyStorage(new string[] {
                "Гостиница"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Гостиница Гостиница
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.Гостиница Get start)

                // *** End programmer edit section *** (РаспОбСотр.Гостиница Get start)
                IIS.Gostinica1.Гостиница result = this.fГостиница;
                // *** Start programmer edit section *** (РаспОбСотр.Гостиница Get end)

                // *** End programmer edit section *** (РаспОбСотр.Гостиница Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.Гостиница Set start)

                // *** End programmer edit section *** (РаспОбСотр.Гостиница Set start)
                this.fГостиница = value;
                // *** Start programmer edit section *** (РаспОбСотр.Гостиница Set end)

                // *** End programmer edit section *** (РаспОбСотр.Гостиница Set end)
            }
        }
        
        /// <summary>
        /// Расп об сотр.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.Директор CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.Директор CustomAttributes)
        [PropertyStorage(new string[] {
                "Директор"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Директор Директор
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.Директор Get start)

                // *** End programmer edit section *** (РаспОбСотр.Директор Get start)
                IIS.Gostinica1.Директор result = this.fДиректор;
                // *** Start programmer edit section *** (РаспОбСотр.Директор Get end)

                // *** End programmer edit section *** (РаспОбСотр.Директор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.Директор Set start)

                // *** End programmer edit section *** (РаспОбСотр.Директор Set start)
                this.fДиректор = value;
                // *** Start programmer edit section *** (РаспОбСотр.Директор Set end)

                // *** End programmer edit section *** (РаспОбСотр.Директор Set end)
            }
        }
        
        /// <summary>
        /// Расп об сотр.
        /// </summary>
        // *** Start programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр CustomAttributes)

        // *** End programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧРаспОбСотр"})]
        [NotNull()]
        public virtual IIS.Gostinica1.ТЧРаспОбСотр ТЧРаспОбСотр
        {
            get
            {
                // *** Start programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Get start)

                // *** End programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Get start)
                IIS.Gostinica1.ТЧРаспОбСотр result = this.fТЧРаспОбСотр;
                // *** Start programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Get end)

                // *** End programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Set start)

                // *** End programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Set start)
                this.fТЧРаспОбСотр = value;
                // *** Start programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Set end)

                // *** End programmer edit section *** (РаспОбСотр.ТЧРаспОбСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РаспОбСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаспОбСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаспОбСотрE", typeof(IIS.Gostinica1.РаспОбСотр));
                }
            }
            
            /// <summary>
            /// "РаспОбСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаспОбСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаспОбСотрL", typeof(IIS.Gostinica1.РаспОбСотр));
                }
            }
        }
    }
}
