//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч оп шт расп.
    /// </summary>
    // *** Start programmer edit section *** (ТЧОпШтРасп CustomAttributes)

    // *** End programmer edit section *** (ТЧОпШтРасп CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч оп шт расп")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧОпШтРаспE", new string[] {
            "Надбавки as \'Надбавки\'",
            "Всего as \'Всего\'",
            "Дата as \'Дата\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'",
            "ОпрШтатРасп as \'Опр штат расп\'",
            "ОпрШтатРасп.Дата as \'Дата\'",
            "Должности as \'Должности\'",
            "Должности.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Персонал.ФИО",
            "ОпрШтатРасп.Дата",
            "Должности.Наименование"})]
    [MasterViewDefineAttribute("ТЧОпШтРаспE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ТЧОпШтРаспE", "ОпрШтатРасп", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    [MasterViewDefineAttribute("ТЧОпШтРаспE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ТЧОпШтРаспL", new string[] {
            "Надбавки as \'Надбавки\'",
            "Всего as \'Всего\'",
            "Дата as \'Дата\'",
            "Персонал.ФИО as \'ФИО\'",
            "ОпрШтатРасп.Дата as \'Дата\'",
            "Должности.Наименование as \'Наименование\'"})]
    public class ТЧОпШтРасп : ICSSoft.STORMNET.DataObject
    {
        
        private double fНадбавки;
        
        private double fВсего;
        
        private System.DateTime fДата;
        
        private IIS.Gostinica1.Персонал fПерсонал;
        
        private IIS.Gostinica1.ОпрШтатРасп fОпрШтатРасп;
        
        private IIS.Gostinica1.Должности fДолжности;
        
        // *** Start programmer edit section *** (ТЧОпШтРасп CustomMembers)

        // *** End programmer edit section *** (ТЧОпШтРасп CustomMembers)

        
        /// <summary>
        /// Всего.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОпШтРасп.Всего CustomAttributes)

        // *** End programmer edit section *** (ТЧОпШтРасп.Всего CustomAttributes)
        public virtual double Всего
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Всего Get start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Всего Get start)
                double result = this.fВсего;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Всего Get end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Всего Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Всего Set start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Всего Set start)
                this.fВсего = value;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Всего Set end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Всего Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОпШтРасп.Дата CustomAttributes)

        // *** End programmer edit section *** (ТЧОпШтРасп.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Дата Get start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Дата Get end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Дата Set start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Дата Set end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Дата Set end)
            }
        }
        
        /// <summary>
        /// Надбавки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОпШтРасп.Надбавки CustomAttributes)

        // *** End programmer edit section *** (ТЧОпШтРасп.Надбавки CustomAttributes)
        public virtual double Надбавки
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Надбавки Get start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Надбавки Get start)
                double result = this.fНадбавки;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Надбавки Get end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Надбавки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Надбавки Set start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Надбавки Set start)
                this.fНадбавки = value;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Надбавки Set end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Надбавки Set end)
            }
        }
        
        /// <summary>
        /// Т ч оп шт расп.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОпШтРасп.Должности CustomAttributes)

        // *** End programmer edit section *** (ТЧОпШтРасп.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Должности Get start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Должности Get start)
                IIS.Gostinica1.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Должности Get end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Должности Set start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Должности Set end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Должности Set end)
            }
        }
        
        /// <summary>
        /// Т ч оп шт расп.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп CustomAttributes)

        // *** End programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп CustomAttributes)
        [PropertyStorage(new string[] {
                "ОпрШтатРасп"})]
        [NotNull()]
        public virtual IIS.Gostinica1.ОпрШтатРасп ОпрШтатРасп
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Get start)

                // *** End programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Get start)
                IIS.Gostinica1.ОпрШтатРасп result = this.fОпрШтатРасп;
                // *** Start programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Get end)

                // *** End programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Set start)

                // *** End programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Set start)
                this.fОпрШтатРасп = value;
                // *** Start programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Set end)

                // *** End programmer edit section *** (ТЧОпШтРасп.ОпрШтатРасп Set end)
            }
        }
        
        /// <summary>
        /// Т ч оп шт расп.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОпШтРасп.Персонал CustomAttributes)

        // *** End programmer edit section *** (ТЧОпШтРасп.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Персонал Get start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Персонал Get start)
                IIS.Gostinica1.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Персонал Get end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОпШтРасп.Персонал Set start)

                // *** End programmer edit section *** (ТЧОпШтРасп.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (ТЧОпШтРасп.Персонал Set end)

                // *** End programmer edit section *** (ТЧОпШтРасп.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧОпШтРаспE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧОпШтРаспE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧОпШтРаспE", typeof(IIS.Gostinica1.ТЧОпШтРасп));
                }
            }
            
            /// <summary>
            /// "ТЧОпШтРаспL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧОпШтРаспL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧОпШтРаспL", typeof(IIS.Gostinica1.ТЧОпШтРасп));
                }
            }
        }
    }
}
