//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gostinica1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч расп об сотр.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРаспОбСотр CustomAttributes)

    // *** End programmer edit section *** (ТЧРаспОбСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч расп об сотр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРаспОбСотрE", new string[] {
            "Номер as \'Номер\'",
            "Обязанности as \'Обязанности\'",
            "ДатаСостав as \'Дата состав\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'",
            "Должности as \'Должности\'",
            "Должности.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Персонал.ФИО",
            "Должности.Наименование"})]
    [MasterViewDefineAttribute("ТЧРаспОбСотрE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ТЧРаспОбСотрE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ТЧРаспОбСотрL", new string[] {
            "Номер as \'Номер\'",
            "Обязанности as \'Обязанности\'",
            "ДатаСостав as \'Дата состав\'",
            "Персонал.ФИО as \'ФИО\'",
            "Должности.Наименование as \'Наименование\'"})]
    public class ТЧРаспОбСотр : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fОбязанности;
        
        private System.DateTime fДатаСостав;
        
        private IIS.Gostinica1.Персонал fПерсонал;
        
        private IIS.Gostinica1.Должности fДолжности;
        
        // *** Start programmer edit section *** (ТЧРаспОбСотр CustomMembers)

        // *** End programmer edit section *** (ТЧРаспОбСотр CustomMembers)

        
        /// <summary>
        /// ДатаСостав.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРаспОбСотр.ДатаСостав CustomAttributes)

        // *** End programmer edit section *** (ТЧРаспОбСотр.ДатаСостав CustomAttributes)
        public virtual System.DateTime ДатаСостав
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Get start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Get start)
                System.DateTime result = this.fДатаСостав;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Get end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Set start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Set start)
                this.fДатаСостав = value;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Set end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.ДатаСостав Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРаспОбСотр.Номер CustomAttributes)

        // *** End programmer edit section *** (ТЧРаспОбСотр.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Номер Get start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Номер Get end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Номер Set start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Номер Set end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Номер Set end)
            }
        }
        
        /// <summary>
        /// Обязанности.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРаспОбСотр.Обязанности CustomAttributes)

        // *** End programmer edit section *** (ТЧРаспОбСотр.Обязанности CustomAttributes)
        [StrLen(255)]
        public virtual string Обязанности
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Обязанности Get start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Обязанности Get start)
                string result = this.fОбязанности;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Обязанности Get end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Обязанности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Обязанности Set start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Обязанности Set start)
                this.fОбязанности = value;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Обязанности Set end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Обязанности Set end)
            }
        }
        
        /// <summary>
        /// Т ч расп об сотр.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРаспОбСотр.Должности CustomAttributes)

        // *** End programmer edit section *** (ТЧРаспОбСотр.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Должности Get start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Должности Get start)
                IIS.Gostinica1.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Должности Get end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Должности Set start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Должности Set end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Должности Set end)
            }
        }
        
        /// <summary>
        /// Т ч расп об сотр.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРаспОбСотр.Персонал CustomAttributes)

        // *** End programmer edit section *** (ТЧРаспОбСотр.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Gostinica1.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Персонал Get start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Персонал Get start)
                IIS.Gostinica1.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Персонал Get end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Персонал Set start)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (ТЧРаспОбСотр.Персонал Set end)

                // *** End programmer edit section *** (ТЧРаспОбСотр.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРаспОбСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРаспОбСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРаспОбСотрE", typeof(IIS.Gostinica1.ТЧРаспОбСотр));
                }
            }
            
            /// <summary>
            /// "ТЧРаспОбСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРаспОбСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРаспОбСотрL", typeof(IIS.Gostinica1.ТЧРаспОбСотр));
                }
            }
        }
    }
}
